name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y g++ rapidjson-dev python3-dev python3-pybind11
      - name: Build library
        run: cd bufr/src && make esoh
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: rodeo-bufr-library
          path: |
            bufr/src/bufresohmsg_py.so
            bufr/src/*.py
            bufr/oscar/oscar_stations_all.json
            bufr/schemas/

