name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "workflow-test"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y g++ rapidjson-dev python3-dev python3-pybind11
      - name: Build
        run: cd bufr/src && make esoh
        shell: bash
      - name: LS
        run: pwd && ls
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: bufresohmsg_py.so
          path: |
            bufr/src/bufresohmsg_py.so
            bufr/src/*.py
